orbs:
  docker: circleci/docker@0.5.17
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          cache_from: 'naofumifujii/$CIRCLE_PROJECT_REPONAME:latest'
          image: naofumifujii/$CIRCLE_PROJECT_REPONAME
          tag: latest
